language: python
python:
- '3.6'
cache:
  - pip
  - npm
  - directories:
    - .cache
env:
  global:
    # Upload credentials
    - secure: "O11eDYmvKFh+NN8tEV55XWGI/jdMQHJnBIFEy/gH4P1H9VSpdtsmAMfCSaVDYGZXzOTHgcRjJrLSJQv/LF8oVswJGTTPIBfWwPtEiXcLmUD1mz1ldST+xBiDXPIB9QOkUXNIEhy+UlK6BdeiIyH5fSw1UB2V3mPjqJNnyyC2Qs9jUREsIUzeYB4QPrgPABtckTMCjwOtUVghhqIZK5NzkZsJJf3g7e2etz/TAhcHZkwg0pOGdJhB60QUHWgjeCoiO7QjQOZy9Xlme39/x4m0njX6V1dTvew8F6C8GE4zQCPeE480y8WS2EeaXUjuelHH4OOeN1IcWk4QpcbDNhRrviFvG/vi2RDYArNA28SKFcZw7nULEdgjGJBFTKj2g7lICVv0dWbYL818Vuh5XBFYUP4jWnD0ecVe4enZAWQYJvzccX4NV1eP7ylGR3a6CKNnyL10vjIkZIxmEUDDzqWmmgquWsstEvwgL2yFNkp/u67brkyP8OW25RBw57gUwucb+Vmf9fWQ53B32zV7w68/muISlYdJE1r4fG8/dldv3J3l8sbt/1cwkybkDULJx+6CeMQUx+aPV80dRSfROVvmUIU/hctHAWCocHY50MtfTrwOJej6R7PPjuYdo2cKcirvOVywiTkB/8iewIJ0l2ruCuFGth9n9KL1RFXIA4Iilig="
    - secure: "PH5fV6+hceYIhYwT/Ju+zZPnqgF+cd1CMhe6Ewxeoo2mDNudzRKPI3bU1GiKeQSNWGaLAR8V/kTLgSOjhTnHO5MCglKYMBlp2XkmExJxfn4PVeKgxaPgWMItPY2hOzZ03oqab3cuatD6+h+81TRegoye9g9N3NM5eo7pyJ+YQwMFlBA8UhgeF+x2VQaZaIKD30+kZJK3VjpmbN56srduEMwIKcLF8HsbjB04IY8so+ZM/sBCR8bhjSvioIQEPd4CtEWsCbA7+A38/902FSX3LVE8mIkSpZGzO5rfhw71j/l7hUHOm2g1LKS6FA4M4lMnOvMHAqOFthLglMugV0QjH4aZJav/kkiUP0KFVfce5ydo/yUFzacswOhVWACL7JlZ9cRUgo8cICItN2nKvyGyiOBlv03e/YSW8ls2i1oVGFee9Esh22EIYjt0zbx/OucXYp8oaXm9p4HfkKcg+gP3hcZnmKKISNwEm7hcRJrhcYIc/hc/WFo9dLYDfN8oNEAFqTqkpn7ZDgMWyUAnfIxZrpCmpLCtHT8vrQunP8hc5Q3lhSO2DDvNgblLoh7/1lWquXc4Mri6g9+6TmzQydluRe4cmPLm16hV029vswGfR8kV2pJCb7AagSz1hRVkxsweI1JMz246zbkNWKUaHnyrIie9sJ/kWF/LF0F36/V4+KY="
    # CloudFront credentials
    - secure: "XR+KBPHYM26MJkcLAIqnZuRUDnAxZHNI/ndM2xeUp/4dcuKOY0ZpfI8lt3EovgiD7MEM4t1QKgT1njBY97KGv/3t3VUG5fm5hvLJaBO5PUvZOBSSq4XPxIvZrQrs8UwrSTx+oyJIZ413Ic32m2qQlb2LcX/bLeS5gVD1K0ihj/ZSqUX7PBaRJghse5rneAK/uRPUQS53ipGRCMLB4ew43i364e2sUz2bR4aQx9G4keGvVA3XEgCmujQcgJH2LvPv1mCknlFHvUlM4ivrSSEUtlPXeFz7Xr61sMK5CTP8kXsh7yMwyK+9igfN1tvPCDGFTrOKWvNqI6ZQPuLRtgjIs89FUI9c4NJHE1ckwDvL/fbsPRthM1q7RW9lhmms0eRcgLrdMV2fOs/m0sq7He5ac9TJTieg78NCW6APM8o8HibcIK/4276tuXvw7ZLue1VrXVHzs89Ag39JdAsJ6E3PwM7NQedX/5jai+Ha5jgPxEuLKiZ4V5l9yzpuddTMygArd7SOr6zvOffWxGBIR3bjMCKI5dq3jqp9e8QD8PPnqfoUl1Td8M9n2iGCl1reshIv6+amBAZTwblaJj56dr5z10SA72H8Id5MsymtKOCKUtfP+KGBu2dmN+aPh9Ez9saC6sZ6KIRYgS9JBQPiakRhHOEfyzPJcQFAc6MSw0U9y2U="
    - secure: "I/LOnh8AEkihOpVTB9jdkjrrBHunny3mgRCHufiVUtF71fiSpBQPEE02zgmqSLQClnLuIUq4KODbqx4obV3HiAkJZBHG6PTgX/QfGyfumxVLlnfBsCNHbwMZY+4wYeX9d6TM17+bNiLeCMiQcDa3yfHsIVhzpTGBzDZGZNmPd1xfQuILAcmLVgoGPjl4SmSRKLpPZMJBprKYMpobpbj0t/oVZ/bg9KM3gv4oQTcipyNeq+4Xkm5MlBeTU3ajr/hM0QbmeviVvMyTLWeg9ghUamm28B4ZQChOPV2tuYpJjF7AGsIsaVMZxGTaxjnXL/Pl5AstzEQAb2aS+p379J1n6NMbOfAP/XYXEeU6td/oY8IOrZ2eFHtt7cJe3R/BWSR6RWD79Vre5fNFUYdWHRbjpfwcySqNxLaY45y/WUgHcLKcDxOI1JwDWKNa2u1ziM21q3pkK9R87id25gcFTspbmpURR0ziH6l+Z95l0XmTj1BH1WWArpOF9j2AqGUPVqMB5So2HD6Ase5adooQUOWekEhcb6Q+S59UxvsVFEHUKA7ALQZ3O+F5zQv24s7v8jy2FM0L5MI9LerXkwXxPMEE3g0JQpxYQTyBXqdJD2MFJEPzurkBPOk5CIV1Qg6D5lVwCdtr+/it5rRgamc/LF4n9L+pLYjibAvx64uka0/qYIg="
    - AWS_BUCKET="20180704-docs-private"
    - AWS_REGION="eu-central-1"
install:
  - nvm install $(cat .nvmrc)
  - travis_retry npm install --no-optional
  - pip install -r requirements.txt
script:
  - make html-production
  - make write-gtm
before_deploy:
  - pip install awscli
deploy:
  on:
    branch: master
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
after_deploy:
  # Bust the CloudFront edge cache, invalidate every object in the distribution
  - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
