language: python
python:
- '3.6'
cache:
  - pip
  - npm
  - directories:
    - .cache
    - /home/travis/.nvm
env:
  global:
    # Upload credentials
    - secure: qA8IivKhQQ4oebUhbj4+jOipwWS8wOF6n7isSp1enlUXybRS1UgahSZ62nrlv1e/jGYw2oh+tdF3R93qa9ej2W+GyqJ2V/GtbgMUR/hSgLkcSN3ay4MgDSmWYRJJFBTpglv7Id3y/4y5oTo6SBjZr6mZ2ylRkOu+FxHlgDHtgk20ophi5hhzt7bTVyFGuZ9jtzPYhbVBrXHdrEKknQfnlOpkhnIjZrBiaZDq1OpliRJT/TRF5wdN0k2NvVLVZsYcaXEZnxOCtz0f4zW4HdgAJek78BSrSQhAxDK54QF3DauZodLKUfVIb2CQr/pXME33OByudA7Ryrroo+r2W8HSsLu69DiSe2U+MHmpf8W4JPhgDW6IwTgJDV8bVwxIrYNdnNax+MiVpXhLoVQD5bkfXMwv2EG5i2+774YYEnrLJxxuiq4YGr0qw+Y0/g8iM8sauVab3FCZjD+i0/YdmivF3lJa0U3KFSKWznqIFbZxKzKrvm8lNwCLgvGbKHG1OOK3KDCekP8Gdl4sOPLG82TUZmo/Gi/2IoQ8s4F9qLvyQ4ANAsSYeDreWv5nysC6nx9Fxk/3gWbOVn9kL7ppJpYYi289IyqNEviMbvw814aNCfooPdquYP3I+rGoIIgRAkwnAM7uq2Qa07BYfzuLNmZi/L6ebIO7HT2s06LiCRvlHD0=
    - secure: ZFLl/A0aJE1bfHcq+DXRwm2t9o29XQsTJWOzFaMpc4rS8rXwCcXhOKN5iAT4o6ZXvxHQRUA+yFr7Xa3L5T1J/lLb3m29Hjrn2xUlyNo8MpT2BDi3dtRZ+mS8abbGyuBEIAq/B67E5G5WZFSUhebnlhvR+304sr8JUcZNvmnI5D8qLxnn7ai5gjb946Q9CIBKyq0aqU2uKK3qrC23/EvmyHP+HgU948URc1/5f5rF08U8j/WnqPXG99+r1on9sqkkIUaD6n2mhEjktk9hREMJNOD/OTB6+rIE2sCeyOHxhEUhHbNh2lw8ZsSeB8XLUOBUXKRuJ8/kks0E3CU6Sk/Dnpbc/q/6hXDA4T+tPp049kt+a5GRwQEBhm3O0UpnLTS77BG6hIZncSyzHnsUSrdNJGxxzY5bG+7E9KbHlpbM1CLvC9qvDko5xyK/dBRmZe6T7kMBnXI7KbXEt5m9LrDMSZ3R0H9bvEFYMfY+6Ql7QXhGNV0AcnnVyZ+AmZP46/Ps6w9gj29HrEBKIlt1Mu+NjXzCIR8WQXl/2xH7nwzRsyAT1bZfaXEg7e3v0H5hwnuAf1wG/giYdn/0167nQwArZ7VlhT0zCWWAj7+qnvX3VEMKgTSw8Hr6/Zsye7AXdkXewalFE414EM4L9HFHiLcD214DpVCsYO8MgPWQoRO5dik=
    # CloudFront credentials
    - secure: Duu5/XtdMQym6uZ+EbWv9Y04e+7pIZjVYrVKJMwN6prj+cMcQtfEOSntFFfqE/g9bcnhb+p9htAVxWXO9iU0EauD9W45X4F2gPY4AiiNE8f73VhnIYZELHqOE+h3uQBZHdu/VqRn6Ao1ovh8hL9G6PtgjJ674IouMfZ823MCxjbf1s/Af52BTqTx5i81O3xX0LknCJmSwp0Muwnua1+k/RHIIoRWqV06nOVn1WVatgDz1cP7a751cCKfTOeMFoYepVaKlh+T3+2hgx4zj23S5Z2w7wv9FSGyzk0pvXq2dbHcL1TZYswixWFetw1xSx8T9wyMKxoHWzgSrhqJ/VxPTv/Ox86YQCWHoMfBnURUSAbUBSCboWi9ssTNt7oRDjt6QCmxuL1IfUsL/4wRWwVu5cJJvvtPkih+s41H3ejPpTeLxyi0JHPoRa5hoiGBjVrXj/4pD5HeruMEl+M5TPkJ0gLSx762RqzWMmYUlJKcaZZJ4wVllftT8U5Yt8tR/t3DHAa2GSvKkMSN3oz1LpPeQrzTacm+nAOo2C0grSPrdnxmo0l3aCYGNyUhtStxV467IcyMVtR/XH327+fOECJo/mSFCo0X0PeaOD4aex8rBS3RnQhOPxFPv8JkLE0DbMzXNDbYJeoYaUtXaJuJ4RKs0BugpeeirXADJxvm0X3doMU=
    - secure: xGU7E+6E9jzjUmPaT3JPcr2EYfX0XaqsKekFuRcDvs904ky8LsDN2xpa9FvlGn0G3qgv5lDhqjyV6b8C8X4Dy3HNJrsMaE0AYVm5Sz89t+CBBSoDUvqBzOYRS8e3+oXILR2DjMxp+TPl+NmYM4LmrjHWcSPAEFoe2B3ofqW3DBM5ecxoqGA6eB4xz9pGtU7YQTWAe9OFBwcYBmQNmhRQHYDtdHvsVtaRuLeOT3qif6qhS3cCm1SVXkPj3j+JFrhJE/el7RT9kHhMF73FhFjPAQ7WTJxRc6s70SEQBT7lMlOA2L65g/aS63GOAl0qMwjSDf4n+SaynF4E6e9VbVZrM57G/XreEIDaOrfodwKtowwHFon3TSNinTXPJH/tp6+TudgYpjjzK6MqieAcd8vWIjEhpFVUEe2tCNf1K/69SZj21PTxZastQ0QTifT+8UVdMY6pDFy7KRr0gfDwIn2pjGvPagXMjBqwd7+eku1+32Hk2wD8GAir/dE4oAsWOEeWvnQDolH7pfdcneTxSNbDjjp1UKQGQ0d5DiXdcEEGnY3kzgA9jEEYT8oK4KaEzxpUtZ82ZCeF3l0A6YY1Ock/IJ0zjgJRxA4lD6y1pco9uiEXGZkxjmOBtBjc6KQpKvV/hZpPmYfZtwnAHeahzJZy3vDZWJlDUfRV8pxEvbieRd8=
    - AWS_BUCKET="20180313-docs"
    - AWS_REGION="eu-central-1"
install:
  - nvm install $(cat .nvmrc)
  - travis_retry npm install --no-optional --no-audit
  - pip install -r requirements.txt
script:
  - make html-production
before_deploy:
  - pip install awscli
deploy:
  on:
    branch: master
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
after_deploy:
  # Bust the CloudFront edge cache, invalidate every object in the distribution
  - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
  - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_CDN_ID} --paths "/*"
